# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4d9e22202eb9116e04fb1a301d35f6ba2d4d88e07e7fc8aeb0cb747de686a385a379518f6d84b5f778e0eea8d4a53a4967d92551ff10f358fba44d740cd76df

test:
  secret_key_base: 8841609ed49bac06f332a604a52c60ab4e0406b744218c4d222b445f64c17f35869397d4b6d4b163f26cb7ff65999406a0d1d7dd4496c0e4c08e38b80e62e6d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
